import "./globals.css";
import Header from "@/components/header";
import Providers from "./providers";
import { Poppins as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
  display: "swap",
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background text-slate-900 antialiased dark:bg-slate-900 dark:text-slate-50",
          fontSans.className
        )}
        style={{ pointerEvents: "auto" }}
      >
        <Providers>
          <Header />
          <main className="flex min-h-screen flex-col items-center justify-between container mx-auto pt-20 ">
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
